ressources = {
    money = {money_cost = 1}, -- money cost is the money required, and spent to buy a ressource
    manpower = {money_cost = 0}, -- manpower can not be bought, it is generated by the population of your country
    iron = {money_cost = 10},
    blackpowder = {money_cost = 2},
    wood = {money_cost = 4},
    stone = {money_cost = 7},
    merchant_ships = {money_cost = 6300}, -- not exactly a ressource but important for trade, the more you have the better
    coal = {money_cost = 1}, -- cheapest ressource, but very important so you'll use a lot
    steel = {money_cost = 15},
    rifles = {money_cost = 5},
    ammunition = {money_cost = 2} -- used by all gunpowder units, so you'll need a lot of it, especially for ships since they have many cannons
}

buildings = {
    factory = {
        money_cost = 10000,
        iron_cost = 10, 
        blackpowder_cost = 0, 
        wood_cost = 20,
        stone_cost = 100,
        steel_cost = 12

    },

    barracks = {
        money_cost = 8700,
        iron_cost = 10, 
        blackpowder_cost = 300, 
        wood_cost = 100,
        stone_cost = 100,
        steel_cost = 0
    }
}

units = {
    infantry = {
        upkeep_cost = 10,
        manpower_cost = 100,
        money_cost = 100,
        iron_cost = 10, 
        ammunition_cost = 5, 
        wood_cost = 0,
        stone_cost = 0,
        steel_cost = 0
    },

    artillery = {
        upkeep_cost = 20,
        manpower_cost = 150,
        money_cost = 500,
        iron_cost = 20, 
        ammunition_cost = 20, 
        wood_cost = 10,
        stone_cost = 0,
        steel_cost = 5
    },

    cavalry = {
        upkeep_cost = 15,
        manpower_cost = 100,
        money_cost = 300,
        iron_cost = 15, 
        ammunition_cost = 10, 
        wood_cost = 0,
        stone_cost = 0,
        steel_cost = 0
    }
}

-- i wonder if i should make it more like victoria 2, where you have to build factories and then they produce ressources, and then you can use those ressources to build units. that would make it more complex but also more interesting. maybe i can add that in a future update. for now, this is a good start.
