local economy = {}

economy.ressources = {
    money = {money_cost = 1}, -- money cost is the money required, and spent to buy a ressource
    manpower = {money_cost = 0}, -- manpower can not be bought, it is generated by the population of your country
    iron = {money_cost = 10},
    blackpowder = {money_cost = 2},
    wood = {money_cost = 4},
    stone = {money_cost = 7},
    merchant_ships = {money_cost = 6300}, -- not exactly a ressource but important for trade, the more you have the better
    coal = {money_cost = 1}, -- cheapest ressource, but very important so you'll use a lot
    steel = {money_cost = 15},
    rifles = {money_cost = 5},
    ammunition = {money_cost = 2} -- used by all gunpowder units, so you'll need a lot of it, especially for ships since they have many cannons
}

economy.buildings = {
    steel_factory = {
        name = "Steel factory",
        money_cost = 10000,
        iron_cost = 10, 
        blackpowder_cost = 0, 
        wood_cost = 20,
        stone_cost = 100,
        steel_cost = 12,
        maxhealth = 10000

    },

    Rifle_factory = {
        name = "Rifle factory",
        money_cost = 10000,
        iron_cost = 10, 
        blackpowder_cost = 0, 
        wood_cost = 20,
        stone_cost = 100,
        steel_cost = 12,
        maxhealth = 9000

    },

    recruitment_center = {
        name = "Recruitment center",
        money_cost = 8700,
        iron_cost = 10, 
        blackpowder_cost = 300, 
        wood_cost = 100,
        stone_cost = 100,
        steel_cost = 0,
        maxhealth = 5000
    }
}

return economy